name: 定时访问 feihukuai

on:
  schedule:
    - cron: '0 16 * * *'
    - cron: '0 22 * * *'
  workflow_dispatch:

jobs:
  visit:
    runs-on: ubuntu-latest
    steps:
      - name: 访问目标网址
        run: |
          curl -sL -A "Mozilla/5.0" "https://feihukuai.lovestoblog.com/" -o /dev/null
          echo "访问完成"
